// Code generated by protoc-gen-go. DO NOT EDIT.
// source: init.proto

package init

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	r2 "r2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 枚举
type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
	SearchRequest_LOCAL     SearchRequest_Corpus = 3
	SearchRequest_NEWS      SearchRequest_Corpus = 4
	SearchRequest_PRODUCTS  SearchRequest_Corpus = 5
	SearchRequest_VIDEO     SearchRequest_Corpus = 6
)

var SearchRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var SearchRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x SearchRequest_Corpus) String() string {
	return proto.EnumName(SearchRequest_Corpus_name, int32(x))
}

func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0, 0}
}

type SearchRequest struct {
	Query                string               `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32                `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32                `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus               SearchRequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=SearchRequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return SearchRequest_UNIVERSAL
}

type Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

// 响应消息类型的属性results，返回的是一个Result类型的消息列表。
type S1Response struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *S1Response) Reset()         { *m = S1Response{} }
func (m *S1Response) String() string { return proto.CompactTextString(m) }
func (*S1Response) ProtoMessage()    {}
func (*S1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{2}
}

func (m *S1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S1Response.Unmarshal(m, b)
}
func (m *S1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S1Response.Marshal(b, m, deterministic)
}
func (m *S1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S1Response.Merge(m, src)
}
func (m *S1Response) XXX_Size() int {
	return xxx_messageInfo_S1Response.Size(m)
}
func (m *S1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_S1Response.DiscardUnknown(m)
}

var xxx_messageInfo_S1Response proto.InternalMessageInfo

func (m *S1Response) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type S2Response struct {
	Results              []*r2.Info `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2Response) Reset()         { *m = S2Response{} }
func (m *S2Response) String() string { return proto.CompactTextString(m) }
func (*S2Response) ProtoMessage()    {}
func (*S2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{3}
}

func (m *S2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2Response.Unmarshal(m, b)
}
func (m *S2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2Response.Marshal(b, m, deterministic)
}
func (m *S2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2Response.Merge(m, src)
}
func (m *S2Response) XXX_Size() int {
	return xxx_messageInfo_S2Response.Size(m)
}
func (m *S2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_S2Response.DiscardUnknown(m)
}

var xxx_messageInfo_S2Response proto.InternalMessageInfo

func (m *S2Response) GetResults() []*r2.Info {
	if m != nil {
		return m.Results
	}
	return nil
}

// 内嵌
type S3Response struct {
	Results              []*S3Response_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S3Response) Reset()         { *m = S3Response{} }
func (m *S3Response) String() string { return proto.CompactTextString(m) }
func (*S3Response) ProtoMessage()    {}
func (*S3Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{4}
}

func (m *S3Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Response.Unmarshal(m, b)
}
func (m *S3Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Response.Marshal(b, m, deterministic)
}
func (m *S3Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Response.Merge(m, src)
}
func (m *S3Response) XXX_Size() int {
	return xxx_messageInfo_S3Response.Size(m)
}
func (m *S3Response) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Response.DiscardUnknown(m)
}

var xxx_messageInfo_S3Response proto.InternalMessageInfo

func (m *S3Response) GetResults() []*S3Response_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type S3Response_Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Response_Result) Reset()         { *m = S3Response_Result{} }
func (m *S3Response_Result) String() string { return proto.CompactTextString(m) }
func (*S3Response_Result) ProtoMessage()    {}
func (*S3Response_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{4, 0}
}

func (m *S3Response_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Response_Result.Unmarshal(m, b)
}
func (m *S3Response_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Response_Result.Marshal(b, m, deterministic)
}
func (m *S3Response_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Response_Result.Merge(m, src)
}
func (m *S3Response_Result) XXX_Size() int {
	return xxx_messageInfo_S3Response_Result.Size(m)
}
func (m *S3Response_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Response_Result.DiscardUnknown(m)
}

var xxx_messageInfo_S3Response_Result proto.InternalMessageInfo

func (m *S3Response_Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *S3Response_Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *S3Response_Result) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func init() {
	proto.RegisterEnum("SearchRequest_Corpus", SearchRequest_Corpus_name, SearchRequest_Corpus_value)
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*Result)(nil), "Result")
	proto.RegisterType((*S1Response)(nil), "S1Response")
	proto.RegisterType((*S2Response)(nil), "S2Response")
	proto.RegisterType((*S3Response)(nil), "S3Response")
	proto.RegisterType((*S3Response_Result)(nil), "S3Response.Result")
}

func init() { proto.RegisterFile("init.proto", fileDescriptor_8d036da5b4a9bcf3) }

var fileDescriptor_8d036da5b4a9bcf3 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0xff, 0xa1, 0xb4, 0xb4, 0x97, 0x1f, 0x99, 0x4c, 0x34, 0x69, 0xd8, 0x58, 0xbb, 0x30,
	0x5d, 0x68, 0xd1, 0xf2, 0x04, 0x08, 0x8d, 0x69, 0x52, 0x81, 0xcc, 0x08, 0x24, 0x6e, 0x08, 0x90,
	0x11, 0x9b, 0x60, 0x5b, 0x66, 0xda, 0x85, 0x6f, 0xe0, 0x2b, 0xbb, 0x33, 0x6d, 0x11, 0x22, 0x6b,
	0x77, 0xbd, 0xdf, 0x3d, 0xa7, 0x67, 0xce, 0x64, 0x00, 0xa2, 0x38, 0xca, 0xdc, 0x54, 0x24, 0x59,
	0xd2, 0x69, 0x0b, 0xaf, 0x2b, 0xb8, 0xcc, 0xb7, 0x7b, 0x60, 0x7f, 0x21, 0x68, 0x31, 0xbe, 0x14,
	0xeb, 0x37, 0xca, 0x77, 0x39, 0x97, 0x19, 0x39, 0x07, 0x75, 0x97, 0x73, 0xf1, 0x61, 0x22, 0x0b,
	0x39, 0x06, 0xad, 0x06, 0x72, 0x09, 0xcd, 0x74, 0xb9, 0xe1, 0x8b, 0x38, 0x7f, 0x5f, 0x71, 0x61,
	0xd6, 0x2c, 0xe4, 0xa8, 0x14, 0x0a, 0x34, 0x2a, 0x09, 0xb9, 0x86, 0x76, 0xf5, 0xe3, 0x45, 0xca,
	0xc5, 0xa2, 0x58, 0x98, 0x4a, 0x29, 0x6a, 0x55, 0x78, 0xc2, 0xc5, 0x64, 0xb9, 0xe1, 0xe4, 0x16,
	0xb4, 0x75, 0x22, 0xd2, 0x5c, 0x9a, 0x75, 0x0b, 0x39, 0x67, 0xde, 0x85, 0xfb, 0x2b, 0xde, 0x1d,
	0x94, 0x4b, 0xba, 0x17, 0xd9, 0x2f, 0xa0, 0x55, 0x84, 0xb4, 0xc0, 0x98, 0x8e, 0x82, 0x99, 0x4f,
	0x59, 0x3f, 0xc4, 0xff, 0x48, 0x03, 0x94, 0xb9, 0xff, 0x80, 0x11, 0x01, 0xd0, 0x82, 0xa7, 0xfe,
	0xa3, 0xcf, 0x70, 0x8d, 0x18, 0xa0, 0x86, 0xe3, 0x41, 0x3f, 0xc4, 0x0a, 0xd1, 0xa1, 0x3e, 0xf2,
	0xe7, 0x0c, 0xd7, 0xc9, 0x7f, 0xd0, 0x27, 0x74, 0x3c, 0x9c, 0x0e, 0x9e, 0x19, 0x56, 0x0b, 0xc9,
	0x2c, 0x18, 0xfa, 0x63, 0xac, 0xd9, 0x21, 0x68, 0xb4, 0x3c, 0x1b, 0xc1, 0xa0, 0xe4, 0x62, 0xbb,
	0x6f, 0x5c, 0x7c, 0x16, 0xb7, 0x90, 0x45, 0xd9, 0x96, 0x97, 0x4d, 0x0d, 0x5a, 0x0d, 0xa4, 0x03,
	0xba, 0x8c, 0xa3, 0x34, 0xe5, 0x99, 0x34, 0x15, 0x4b, 0x71, 0x0c, 0x7a, 0x98, 0xed, 0x2e, 0x00,
	0xbb, 0xa7, 0x5c, 0xa6, 0x49, 0x2c, 0x39, 0xb9, 0x82, 0x46, 0xd5, 0x5b, 0x9a, 0xc8, 0x52, 0x9c,
	0xa6, 0xd7, 0x70, 0xab, 0x2c, 0xfa, 0xc3, 0xed, 0x3b, 0x00, 0xe6, 0x1d, 0x0c, 0xf6, 0xa9, 0x41,
	0x77, 0x85, 0xe7, 0x06, 0xf1, 0x6b, 0x72, 0x74, 0x7c, 0x22, 0x00, 0xd6, 0x3b, 0x58, 0x6e, 0x4e,
	0x2d, 0xc4, 0x3d, 0x6e, 0x4f, 0xe3, 0x3a, 0x7f, 0xda, 0x76, 0xa5, 0x95, 0xcf, 0xa7, 0xf7, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xff, 0x31, 0x42, 0x13, 0x5d, 0x02, 0x00, 0x00,
}
